# Generated by Django 4.2.5 on 2024-06-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee_data',
        ),
    ]
