# Generated by Django 4.2.5 on 2024-06-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_employee', '0002_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
