# Generated by Django 5.2 on 2025-09-11 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_employee', '0003_alter_employee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentEmployeeCounts',
            fields=[
                ('dept_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=255)),
                ('total_employees', models.BigIntegerField()),
            ],
            options={
                'db_table': 'department_employee_counts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeDepartmentView',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('department_id', models.CharField(max_length=4)),
                ('department_name', models.CharField(max_length=40)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
            options={
                'db_table': 'employee_department_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryHike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField()),
                ('from_date', models.DateField()),
                ('current_salary', models.IntegerField()),
                ('previous_salary', models.IntegerField()),
                ('hike_percentage', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_no', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('emp_no', models.ForeignKey(db_column='emp_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='view_employee.employee')),
                ('title', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'title',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('emp_no', models.ForeignKey(db_column='emp_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='view_employee.employee')),
                ('amount', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
            options={
                'db_table': 'salary',
                'unique_together': {('emp_no', 'from_date')},
            },
        ),
        migrations.CreateModel(
            name='DeptEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('dept_no', models.ForeignKey(db_column='dept_no', on_delete=django.db.models.deletion.CASCADE, to='view_employee.department')),
                ('emp_no', models.ForeignKey(db_column='emp_no', on_delete=django.db.models.deletion.CASCADE, to='view_employee.employee')),
            ],
            options={
                'db_table': 'dept_emp',
                'unique_together': {('emp_no', 'dept_no')},
            },
        ),
    ]
