# Generated by Django 5.2 on 2025-09-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_employee', '0004_departmentemployeecounts_employeedepartmentview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='emp_no',
            field=models.OneToOneField(db_column='emp_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='view_employee.employee'),
        ),
        migrations.AlterField(
            model_name='title',
            name='emp_no',
            field=models.OneToOneField(db_column='emp_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='view_employee.employee'),
        ),
    ]
