# Generated by Django 5.2 on 2025-09-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_employee', '0005_alter_salary_emp_no_alter_title_emp_no'),
        ('view_employee', '0006_create_department_employee_counts_view'),
    ]

    operations = [
    ]
