# Generated by Django 5.2 on 2025-09-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_employee', '0007_merge_20250911_2252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaryHike',
        ),
    ]
