# Generated by Django 5.2 on 2025-09-12 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_employee', '0008_delete_salaryhike'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryHike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('current_salary', models.IntegerField()),
                ('previous_salary', models.IntegerField()),
                ('hike_percentage', models.DecimalField(decimal_places=1, max_digits=5)),
                ('emp_no', models.ForeignKey(db_column='emp_no', on_delete=django.db.models.deletion.CASCADE, to='view_employee.employee')),
            ],
            options={
                'db_table': 'salary_hike',
                'managed': True,
            },
        ),
    ]
