# Generated by Django 5.2 on 2025-09-12 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_employee', '0009_salaryhike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='emp_no',
            field=models.ForeignKey(db_column='emp_no', on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='view_employee.employee'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='from_date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
