# Generated by Django 5.2 on 2025-09-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeelogin',
            name='id',
        ),
        migrations.AddField(
            model_name='employeelogin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeelogin',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeelogin',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeelogin',
            name='login_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeelogin',
            name='emp_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='employeelogin',
            table='employee_login',
        ),
    ]
